In [1]:
# importing the library 

import numpy as np

In [61]:
# 1D array

array_1d = np.array([1,2,3,4,5], dtype='int32')

array_1d.dtype

print(array_1d.flatten())

[1 2 3 4 5]


In [11]:
# 2d array
a_2d = np.array([[10,11,12,13],[14,13,15,16]])
print(a_2d.shape)
print(a_2d.dtype)


(2, 4)
int64


In [21]:
# 3d array
a_3d = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

a_3d

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [22]:
a_4d = np.array([[[[1,2,3,4],[1,2,3,4],[1,2,3,4]]],[[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])

a_4d

array([[[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]],


       [[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]]])

In [23]:
# Checking the shape to know the rows and column

print(array_1d.shape)
print(a_2d.shape)
print(a_3d.shape)
print(a_4d.shape)

(5,)
(2, 4)
(1, 3, 4)
(2, 1, 3, 4)


In [25]:
print(array_1d.size)
print(a_2d.size)

5
8


In [30]:
a_2d.reshape(4,2)

array([[10, 11],
       [12, 13],
       [14, 13],
       [15, 16]])

In [54]:
a_3d.size

12

In [57]:
a_3d.reshape(2,6)

array([[1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4]])

In [38]:
a_3d.shape

(1, 3, 4)

In [64]:
# flatten

a_3d.flatten().flatten().flatten()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [36]:
a_4d.shape

(2, 1, 3, 4)

In [37]:
a_4d

array([[[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]],


       [[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]]])

In [49]:
a_4d.size

24

In [53]:
a_4d.reshape(4,6)

array([[1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4]])

In [70]:
# transpose

a = np.array([[1,2,3,4],[2,3,4,5],[6,7,8,9]])

print(a)

print('\n')
transpose = a.T

print(transpose)

[[1 2 3 4]
 [2 3 4 5]
 [6 7 8 9]]


[[1 2 6]
 [2 3 7]
 [3 4 8]
 [4 5 9]]


In [75]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])


a = np.concatenate((array1,array2),axis=1)

b = np.concatenate((array1,array2),axis=0)

print(a)

print('\n')
print(b)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [76]:
np.split(b,2,axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [81]:
np.vsplit(a,2)

[array([[1, 2, 3, 7, 8, 9]]), array([[ 4,  5,  6, 10, 11, 12]])]

In [79]:
np.hsplit(a,3)

[array([[1, 2],
        [4, 5]]),
 array([[ 3,  7],
        [ 6, 10]]),
 array([[ 8,  9],
        [11, 12]])]

In [89]:
array = np.array([1, 2, 3, 4, 5])

result = np.delete(array,[1,-2])

result
# np.delete(result,[2])

array([1, 3, 5])

In [97]:
custome_array = np.random.uniform(1,10,size=3)

custome_array

array([2.63739493, 5.46514247, 8.61287044])

In [104]:
np.random.seed(10)

# Generating random numbers
random_numbers = np.random.rand(5)
print("Random Numbers:", random_numbers)

# Resetting the seed to reproduce the same sequence
np.random.seed(10)
reproduced_numbers = np.random.rand(5)
print("Reproduced Numbers:", reproduced_numbers)

Random Numbers: [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
Reproduced Numbers: [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]


In [122]:
number = np.array([1,2,3,4,5,6,7,8])

data = np.random.choice(number,3,replace=False)

data

array([6, 3, 1])